# Generated by Django 4.2.5 on 2024-02-16 17:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, default=1)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=150)),
                ('image', models.ImageField(default='', upload_to='uploads/customers')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('Foods', 'Foods'), ('Book', 'Book'), ('Outfit', 'Outfit')], default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, default=1)),
                ('store_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=150)),
                ('image', models.ImageField(default='', upload_to='uploads/sellers')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('transaction_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=None)),
                ('image', models.ImageField(default=None, upload_to='uploads/product')),
                ('memory_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('ram_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=30, null=True)),
                ('stock', models.IntegerField(default=None)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Second-hand', 'Second-hand')], default='', max_length=30)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Sony', 'Sony'), ('Evercross', 'Evercross'), ('Vivo', 'Vivo'), ('Huawei', 'Huawei'), ('ASUS', 'ASUS'), ('Nokia', 'Nokia'), ('OPPO', 'OPPO'), ('Realme', 'Realme'), ('Infinix', 'Infinix'), ('Lenovo', 'Lenovo')], default='', max_length=30)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('seller_Address', models.CharField(blank=True, max_length=80, null=True)),
                ('categories', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stores.sellers')),
            ],
            options={
                'verbose_name_plural': 'Smartphones',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=255, unique=True)),
                ('email_validated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
