# Generated by Django 4.2.5 on 2024-02-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='owner_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
