# Generated by Django 4.2.5 on 2024-02-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stores.products'),
        ),
    ]
