# Generated by Django 4.2.5 on 2024-02-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_smartphone_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=None)),
                ('image', models.ImageField(default=None, upload_to='uploads/product')),
                ('storage_period', models.CharField(blank=True, max_length=30, null=True)),
                ('storage_condition', models.CharField(blank=True, max_length=30, null=True)),
                ('product_weight', models.CharField(blank=True, max_length=30, null=True)),
                ('number_product', models.CharField(blank=True, max_length=30, null=True)),
                ('stock', models.IntegerField(default=None)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('seller_Address', models.CharField(blank=True, max_length=80, null=True)),
                ('categories', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stores.sellers')),
            ],
            options={
                'verbose_name_plural': 'Foods',
            },
        ),
    ]
