# Generated by Django 4.2.5 on 2024-02-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_products_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='sellers',
            options={'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='products',
            name='formatted_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
