# Generated by Django 4.2.5 on 2024-02-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_customers_password_remove_sellers_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('ram_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=30, null=True)),
                ('stock', models.IntegerField(default='')),
                ('seller_Address', models.CharField(blank=True, max_length=30, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Second-hand', 'Second-hand')], default='', max_length=30)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Sony', 'Sony'), ('Evercross', 'Evercross'), ('Vivo', 'Vivo'), ('Huawei', 'Huawei'), ('ASUS', 'ASUS'), ('Nokia', 'Nokia'), ('OPPO', 'OPPO'), ('Realme', 'Realme'), ('Infinix', 'Infinix'), ('Lenovo', 'Lenovo')], default='', max_length=30)),
            ],
        ),
    ]
