# Generated by Django 4.2.5 on 2024-02-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_foods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='categories',
            new_name='food_categories',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='description',
            new_name='food_description',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='image',
            new_name='food_image',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='owner',
            new_name='food_owner',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='price',
            new_name='food_price',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='seller_Address',
            new_name='food_seller_Address',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='stock',
            new_name='food_stock',
        ),
    ]
