# Generated by Django 4.2.5 on 2024-02-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_rename_categories_foods_food_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('pictures', models.ImageField(default=None, upload_to='uploads/comment_smartphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.smartphone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.customers')),
            ],
            options={
                'verbose_name_plural': 'Comment_Smartphone',
            },
        ),
    ]
