# Generated by Django 4.2.5 on 2024-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_smartphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartphone',
            options={'verbose_name_plural': 'Smartphones'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name',
        ),
        migrations.AddField(
            model_name='categories',
            name='categories',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('Foods', 'Foods'), ('Book', 'Book'), ('Outfit', 'Outfit')], default='', max_length=50),
        ),
    ]
