# Generated by Django 4.2.5 on 2024-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/customers'),
        ),
        migrations.AddField(
            model_name='sellers',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/sellers'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
