# Generated by Django 4.2.5 on 2024-03-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_shopping_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopping_cart',
            options={'verbose_name_plural': 'Shopping_Cart'},
        ),
    ]
