# Generated by Django 4.2.5 on 2024-03-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_shopping_cart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='address',
        ),
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='customers',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='district',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='customers',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customers',
            name='province',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='customers',
            name='street',
            field=models.CharField(default='', max_length=200),
        ),
    ]
