# Generated by Django 4.2.5 on 2024-03-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_customers_address_customers_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellers',
            name='address',
        ),
        migrations.AddField(
            model_name='sellers',
            name='city',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='sellers',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sellers',
            name='district',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='sellers',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sellers',
            name='province',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='sellers',
            name='street',
            field=models.CharField(default='', max_length=200),
        ),
    ]
