# Generated by Django 4.2.5 on 2024-03-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_remove_sellers_address_sellers_city_sellers_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='owner_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
