# Generated by Django 4.2.5 on 2024-03-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_customers_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='owner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.profile'),
        ),
    ]
