# Generated by Django 4.2.5 on 2024-03-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_alter_customers_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('Regular', 'Regular'), ('Fast', 'Fast'), ('Cargo', 'Cargo')], default='', max_length=100)),
                ('price', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Shipping Type',
            },
        ),
    ]
